### ISSUE TITLE
Broken release

### ISSUE THREAD

**Issue by KanadeEngel** [MRGhidini/Psvimgtools-Easy-FrontEnd#1]
Your Tool are using the Account ID instead of the Key which is needed to de-/encrypt the *.psvimg format

The de-/encryption key have also to be generated by this site http://cma.henkaku.xyz/?aid=

**Comment by MRGhidini** [comment]
The tool uses the QCMA ID and goes to the site example: http://cma.henkaku.xyz/?aid=03cca8e096e64b6, search the key and extract the psvimg !, please do new test!
