### ISSUE TITLE
why your UI be so little?

### ISSUE THREAD

**Issue by GitHubyoyo** [MRGhidini/Psvimgtools-Easy-FrontEnd#11]
>
![image 1](https://user-images.githubusercontent.com/32557886/31289894-17b42ca8-aafd-11e7-9c3c-a7ea7cb674d6.jpg)

I can not switch buttom in the window.  (example: "OK" buttom)
How can I do? THX

My system: WIN7 64BIT

**Comment by GitHubyoyo** [comment]
oh,I use software "ResizeEnable".

It's OK now.

**Comment by MRGhidini** [comment]
Hello dude, how are you ?
Thanks for comment.
When I created it, I thought of a simple interface, so small size is better.
