### ISSUE TITLE
Cant extract pkg with 1.7.4

### ISSUE THREAD

**Issue by Bryguy5849** [MRGhidini/Psvimgtools-Easy-FrontEnd#13]
It keeps giving me the error "The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem.". Im able to use 1.7.3 to extract just fine but no matter what I try, 1.7.4 wont work.

**Comment by MRGhidini** [comment]
Morning.
See if you have updates from pending on windows, the missing dll seems to be this problem
