### ISSUE TITLE
can't add IDWEB

### ISSUE THREAD

**Issue by chronoss09** [MRGhidini/Psvimgtools-Easy-FrontEnd#18]
![e07238e1bd3ba8c4b277f4aa878387e7](https://user-images.githubusercontent.com/17669980/42170381-45cd49f0-7e0e-11e8-8632-59666b05ef40.png)

**Comment by MRGhidini** [comment]
Are you still wrong, my friend?

**Comment by chronoss09** [comment]
Sorry, it's my PC. I have a problem with that :(

**Comment by MRGhidini** [comment]
Ok My friend. I hope that you repairs.
Thank you =)
