### ISSUE TITLE
Name of game after/before Title ID

### ISSUE THREAD

**Issue by chronoss09** [MRGhidini/Psvimgtools-Easy-FrontEnd#2]
Sorry but i don't know how to create the Pull request.

The only thing i want to ask you is if you can make the name of game after or before their Title ID when you want choose the game that would be patched

Exemple : 
<a href="https://gyazo.com/112a83ae0734d320712e9f4a37d5f487"><img src="https://i.gyazo.com/112a83ae0734d320712e9f4a37d5f487.png" alt="https://gyazo.com/112a83ae0734d320712e9f4a37d5f487" width="529"/></a>

**Comment by chronoss09** [comment]
Ok thanks ;)

**Comment by MRGhidini** [comment]
Ready, added along with other fixes =)
