### ISSUE TITLE
IDWEB incorrect

### ISSUE THREAD

**Issue by Wannab** [MRGhidini/Psvimgtools-Easy-FrontEnd#21]
when adding idweb this text shows up in the textbox

pe="text" name="aid">
<input type="submit">
</form>

<b>3bdb5

**Comment by MRGhidini** [comment]
https://github.com/MRGhidini/Psvimgtools-Easy-FrontEnd/releases/tag/1.8.4
spoken before version that generates the CMA offiline does not search more of the web with this will not be the error more, please test
