### ISSUE TITLE
Some inssues

### ISSUE THREAD

**Issue by chronoss09** [MRGhidini/Psvimgtools-Easy-FrontEnd#4]
It's not an issue but can u make something to delete a bubble without to conect a vita ?

And, i want to install a theme on my vita in 3.65 but when i press "SQL/app.db" or "Theme/app.db", an empty box appear and i can't do anything :(

And, i can't clone my psp game twice and when i clone a clone of my game psp, i can't install install anything inside

<a href="https://gyazo.com/acf0a00040d0919ca3cfe6b61b2c4932"><img src="https://i.gyazo.com/acf0a00040d0919ca3cfe6b61b2c4932.png" alt="https://gyazo.com/acf0a00040d0919ca3cfe6b61b2c4932" width="499"/></a>

**Comment by MRGhidini** [comment]
Hello friend 
Let's talk about
It's not an issue but can u make something to delete a bubble without to conect a vita ?
**Answering:** **I imagine, you tried to delete a cloned bubble, this not aplicat. why your ps vita going removed too license of your game, what is this ? your license is single, not is possible for cloned**

And, i want to install a theme on my vita in 3.65 but when i press "SQL/app.db" or "Theme/app.db", an empty box appear and i can't do anything :(
**Answering:** **I help you =), on this option he searching you backup, inside this folder SYSTEM. I maked video tutorial - https://www.youtube.com/watch?v=M9JhdNs5VqU**

And, i can't clone my psp game twice and when i clone a clone of my game psp, i can't install install anything inside
**Answering:** Try this tutorial
https://www.youtube.com/watch?v=QJN7xYVrpO8

The tutorial is in Portuguese, I am learning to speak English.
See if it helps you, if yes let me to close the issue log =)

**Comment by chronoss09** [comment]
Ok thanks, very useful video and i have my answer. you can close the issue and good luck for next updates ;)
