### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by One-life-remains** [MRGhidini/Psvimgtools-Easy-FrontEnd#6]
I follow the instruction but when I go to the setting there's a blank square and when I try to apply it I receive this error code. 

![2017-07-18-200713](https://user-images.githubusercontent.com/30279809/28349150-d53302aa-6bf5-11e7-975d-37e5dd1040d5.jpg)

**Comment by MRGhidini** [comment]
Hello my friend.
Could you give me the thema you tried to add?

**Comment by One-life-remains** [comment]
http://psv.altervista.org/theme.php?id=1470398174 
This is the theme

**Comment by MRGhidini** [comment]
I liked the theme
![2017-07-30-182128](https://user-images.githubusercontent.com/26291894/28757276-4100c64e-7555-11e7-9eea-8c301646e74b.jpg)
![2017-07-30-182047](https://user-images.githubusercontent.com/26291894/28757277-44bdc714-7555-11e7-9ced-345e1c761f78.jpg)
As you can see it works normal.
I think you'll have to do it again.
But you will have to delete the line in your database if you try to try.
Use the options below to manually extract.
![capturar](https://user-images.githubusercontent.com/26291894/28757299-c5245aa8-7555-11e7-8656-67c56f65e545.JPG)
After extracting, run the command in sqlite
delete from tbl_theme where id = 'ux0:user/CustomTheme/Nighttime'
Recreate your backup.
And try again to add your theme.

**Comment by One-life-remains** [comment]
Well I got it to work but when I switched mem cards it went to the default theme sadly. I would do it on the other memory card but it's a 32 gb and would take hours to backup.

**Comment by SilicaAndPina** [comment]
Theming was patched in 3.65, thats why.
