### ISSUE TITLE
language for the installer and the programm

### ISSUE THREAD

**Issue by chronoss09** [MRGhidini/Psvimgtools-Easy-FrontEnd#9]
Installer is in Portuguese and some work in the programm have the same language
<a href="https://gyazo.com/1753bc8d3b6403baa25b558196b2cc34"><img src="https://i.gyazo.com/1753bc8d3b6403baa25b558196b2cc34.png" alt="https://gyazo.com/1753bc8d3b6403baa25b558196b2cc34" width="213"/></a>

**Comment by MRGhidini** [comment]
Sorry my friend, the message went unnoticed, I will correct

**Comment by chronoss09** [comment]
Ok thanks but can you make the listing of .pkg with the name of the game ?

**Comment by MRGhidini** [comment]
The only option for this would be to create a db to store the titleid and the name

**Comment by MRGhidini** [comment]
https://github.com/MRGhidini/Psvimgtools-Easy-FrontEnd/releases

Fixed the problem of listing the titleId with underline for some pkg
Fixed issue with language for some messages
Thanks for reporting

**Comment by MRGhidini** [comment]
About this.
Ok thanks but can you make the listing of .pkg with the name of the game ?
can you open a new issue log ?
I'll think of some solution for this
Thanks
